distill_site/common/urls.py
from django_distill import distill_path
from .views import favicon_view, robots_view, _headers_view, error404_view


app_name = 'common'


urlpatterns = [

    distill_path('favicon.ico',
                 favicon_view,
                 name='favicon'),

    distill_path('robots.txt',
                 robots_view,
                 name='robots'),

    distill_path('_headers',
                 _headers_view,
                 name='_headers'),

    distill_path('404.html',
                 error404_view,
                 name='error404',
                 distill_status_codes=(200, 404)),

]

distill_site/content/urls.py
from django_distill import distill_path
from .views import index_view, yamlmd_page_view


app_name = 'content'


def iter_yamlmd_pages():
    """
        A static list of the page names to be generated in
        content/static_content. You could make this dynamic from a query
        or from a glob() style file matching.
    """
    for page_name in (
            'deployment',
            'development',
            'guide-aws-s3',
            'guide-cloudflare-pages',
            'guides',
            'install',
            'integration'
        ):
        yield {'page_name': page_name}


urlpatterns = [

    distill_path('',
                 index_view,
                 name='index',
                 distill_file='index.html'),

    distill_path('<slug:page_name>',
                 yamlmd_page_view,
                 name='yamlmd_page',
                 distill_func=iter_yamlmd_pages),

]

distill_site/distill_site/urls.py
from django.urls import path, include
from django.contrib import admin


admin.site.site_title = 'Django Distill site admin'
admin.site.site_header = 'Django Distill site admin'


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('', include('content.urls')),

]

distill_site/common/models.py
from django.db import models

distill_site/content/models.py
from django.db import models


class Stargazer(models.Model):
    """
        GitHub stargazers for the specified project.
    """

    id = models.PositiveIntegerField(
        primary_key=True,
        help_text='GitHub user ID'
    )
    name = models.CharField(
        max_length=200,
        unique=True,
        db_index=True,
        help_text='GitHub username'
    )
    url = models.URLField(
        help_text='GitHub user profile URL'
    )
    avatar = models.URLField(
        help_text='GitHub user avatar URL'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Stargazer'
        verbose_name_plural = 'Stargazers'
        ordering = ('name',)


class Release(models.Model):
    """
        PyPI releases for the specified project.
    """

    version = models.CharField(
        max_length=16,
        db_index=True,
        help_text='Version of the release'
    )
    url = models.URLField(
        help_text='URL of the release'
    )
    published = models.DateTimeField(
        db_index=True,
        help_text='Date and time of the release'
    )

    def __str__(self):
        return self.version

    class Meta:
        verbose_name = 'Release'
        verbose_name_plural = 'Releases'
        ordering = ('-published',)

    @classmethod
    def get_latest(obj):
        try:
            return obj.objects.order_by('-published')[0]
        except IndexError:
            return None

distill_site/common/views.py
from pathlib import Path
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render
from content.urls import iter_yamlmd_pages


BASE_DIR = Path(__file__).resolve().parent.parent
DOMAIN_NAME = getattr(settings, 'DOMAIN_NAME')


def favicon_view(request):
    favicon = BASE_DIR / 'common' / 'static' / 'images' / 'favicon.ico'
    with open(str(favicon), 'rb') as f:
        data = f.read()
    return HttpResponse(data, content_type='image/x-icon')


def robots_view(request):
    content = '\n'.join([
        'User-agent: *',
        'Allow: /',
    ])
    return HttpResponse(content, content_type='text/plain')


def _headers_view(request):
    content = [
        f'https://:project.pages.dev/*',
        f'  X-Robots-Tag: noindex',
        f'  Location: https://{DOMAIN_NAME}/',
        f'',
        f'/*',
        f'  X-Frame-Options: DENY',
        f'  X-Content-Type-Options: nosniff',
        f'  Referrer-Policy: no-referrer',
        f'  Permissions-Policy: document-domain=()',
        f'  Content-Security-Policy: script-src \'self\'; frame-ancestors \'none\';',
        f'',
        f'/',
        f'  Content-Type: text/html',
        f'/index.html',
        f'  Content-Type: text/html'
    ]
    for page in iter_yamlmd_pages():
        page_name = page['page_name']
        content.append(f'/{page_name}')
        content.append(f'  Content-Type: text/html')
    return HttpResponse('\n'.join(content), content_type='text/plain')


def error404_view(request):
    return render(request, 'error404.html', status=404)

distill_site/content/views.py
from django.shortcuts import render
from content.content import markdown_render, static_page_render
from content.models import Release, Stargazer


def index_view(request):
    num_stargazers_to_show = 144  # divisible by 12 looks nicer in columns
    num_stargazers = Stargazer.objects.all().count()
    return render(request, 'content/index.html', context={
        'intro': markdown_render('index-intro'),
        'how_it_works': markdown_render('index-how-it-works'),
        'latest_release': Release.get_latest(),
        'num_stargazers': num_stargazers,
        'num_stargazers_to_show': num_stargazers_to_show,
        'num_stargazers_remaining': num_stargazers - num_stargazers_to_show,
        'stargazers': Stargazer.objects.order_by('?')[:num_stargazers_to_show]
    })


def yamlmd_page_view(request, page_name):
    header, content = static_page_render(page_name)
    return render(request, 'content/page.html', context={
        'active_page': page_name,
        'header': header,
        'content': content
    })

distill_site/common/templates/base.html
{% load static %}{% load cdnstaticfiles %}{% load sass_tags %}{% load i18n %}<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block page_title %}Static site generator for Django{% endblock %} - Django Distill</title>
    <meta name="description" content="django-distill, a static site generator for Django">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% cdnstatic 'images/favicon.ico' %}">
    <link rel="stylesheet" href="{% sass_src 'styles/distill.scss' %}?tag={% cdntag 'derp' %}">
  </head>

  <body>

    <nav class="navbar main-nav" role="navigation" aria-label="main navigation">
      <div class="navbar-brand is-flex-tablet">
        <a class="navbar-item" href="{% url 'content:index' %}">
          <h1>django-distill</h1>
        </a>
      </div>
      <a class="navbar-item is-expanded{% if active_page == 'install' %} is-active{% endif %}" href="{% url 'content:yamlmd_page' page_name='install' %}">
        <i class="fa-solid fa-fw fa-file-import"></i>&nbsp;Install
      </a>
      <a class="navbar-item is-expanded{% if active_page == 'integration' %} is-active{% endif %}" href="{% url 'content:yamlmd_page' page_name='integration' %}">
        <i class="fa-solid fa-fw fa-puzzle-piece"></i>&nbsp;Integration
      </a>
      <a class="navbar-item is-expanded{% if active_page == 'deployment' %} is-active{% endif %}" href="{% url 'content:yamlmd_page' page_name='deployment' %}">
        <i class="fa-solid fa-fw fa-cloud-arrow-up"></i>&nbsp;Deployment
      </a>
      <a class="navbar-item is-expanded{% if active_page == 'guides' %} is-active{% endif %}" href="{% url 'content:yamlmd_page' page_name='guides' %}">
        <i class="fa-solid fa-fw fa-book-open"></i>&nbsp;Guides
      </a>
      <a class="navbar-item is-expanded{% if active_page == 'development' %} is-active{% endif %}" href="{% url 'content:yamlmd_page' page_name='development' %}">
        <i class="fa-solid fa-fw fa-code"></i>&nbsp;Development
      </a>
    </nav>

  {% block hero %}{% endblock %}

  <div id="content">
{% block content %}{% endblock %}
  </div>

  <footer>
    All content &copy;{% now 'Y' %} the <strong>django-distill</strong> project.
    &quot;Django&quot; is a registered trademark of the Django Software Foundation.
    <strong>django-distill</strong> is an independant project and not part of the Django Software Foundation.
  </footer>

  </body>
</html>

distill_site/common/templates/error404.html
{% extends 'base.html' %}

{% block hero %}
<div class="triangles">
  <section class="hero container">
    <div class="hero-body">
      <p class="title is-size-1-desktop is-size-2-tablet is-size-3-mobile">
        Error 404
      </p>
      <p class="subtitle is-size-3-desktop is-size-4-tablet is-size-5-mobile">
        Page not found
      </p>
    </div>
  </section>
</div>
{% endblock %}

{% block content %}
<section class="container">
  <p>The page you requested does not exist.</p>
</section>
{% endblock %}

distill_site/content/templates/content/index.html
{% extends 'base.html' %}

{% block page_title %}Static site generator for Django{% endblock %}

{% block hero %}
<div class="triangles">
  <section class="hero container side-pad">
    <div class="hero-body">
      <div class="columns">
        <div class="column is-two-thirds is-full-mobile">
          <p class="title is-size-1-desktop is-size-2-tablet is-size-3-mobile">
            django-distill
          </p>
          <p class="subtitle is-size-3-desktop is-size-4-tablet is-size-5-mobile">
            Static site generator for Django
          </p>
        </div>
        <div class="column is-one-third is-full-mobile">
          <div class="block">
            <a class="button is-large is-fullwidth" href="https://github.com/meeb/django-distill/"><i class="fa-brands fa-fw fa-github"></i>&nbsp;GitHub</a>
          </div>
          <div class="block">
            <a class="button is-large is-fullwidth" href="https://pypi.org/project/django-distill/"><i class="fa-brands fa-fw fa-python"></i>&nbsp;PyPI</a>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}

{% block content %}

<section class="container">
  {{ intro|safe }}
</section>

<section class="container side-pad">
  <div class="columns">
    <div class="column is-two-thirds is-full-mobile">
      <h2 class="title">How it works</h2>
      {{ how_it_works|safe }}
    </div>
    <div class="column is-one-third is-full-mobile">
      <div class="box">
        <div class="block">
          <h2 class="title"><i class="fa-solid fa-terminal"></i>&nbsp;Install</h2>
          <div class="icon-field">
            <i class="fa-solid fa-dollar-sign"></i>
            <input class="input install-copypaste" type="text" value="pip install django-distill" readonly="readonly">
          </div>
        </div>
        <div class="block">
          Alternatively, you can <a href="{{ latest_release.url }}#files" rel="nofollow"><i class="fa-solid fa-download"></i> download the release from PyPI</a> as a Python package
        </div>
      </div>
      <div class="block">
        <p>
          The latest release of <strong>django-distill</strong> is <strong>{{ latest_release.version }}</strong> published
          on the <strong>{{ latest_release.published|date:'jS \o\f F Y' }}</strong>
        </p>
        <p>
          <a href="https://pypi.org/project/django-distill/#history" rel="nofollow"><i class="fa-solid fa-clock-rotate-left"></i> View historical releases</a>
        </p>
      </div>
      <div class="box">
        <div class="block">
          <h2 class="title"><i class="fa-solid fa-question"></i>&nbsp;Did you know</h2>
          This website is powered by <strong>Django</strong>, uses <strong>django-distill</strong>
          and is automatically deployed as a static site to Cloudflare pages! This site is open source and you
          can <a href="https://github.com/meeb/django-distill-site/"><i class="fa-brands fa-github"></i> view it on GitHub</a>.
        </div>
      </div>
    </div>
  </div>
</section>

<section class="container side-pad">
  <div class="columns">
    <div class="column is-one-third is-full-mobile">
      <h3 class="title"><i class="fa-solid fa-fw fa-file-import"></i>&nbsp;Install</h3>
      <div class="block">
        For the step by step guide on how to install <strong>django-distill</strong> into
        your Django project, read the
        <a href="{% url 'content:yamlmd_page' page_name='install' %}"><i class="fa-solid fa-fw fa-file-import"></i> installation documentation</a>.
      </div>
    </div>
    <div class="column is-one-third is-full-mobile">
      <h3 class="title"><i class="fa-solid fa-fw fa-puzzle-piece"></i>&nbsp;Integrate</h3>
      <div class="block">
        Installed <strong>django-distill</strong> into your Django project? You can start using
        the full set of static site generation features, read the
        <a href="{% url 'content:yamlmd_page' page_name='integration' %}"><i class="fa-solid fa-fw fa-puzzle-piece"></i> integration documentation</a>.
      </div>
    </div>
    <div class="column is-one-third is-full-mobile">
      <h3 class="title"><i class="fa-solid fa-fw fa-cloud-arrow-up"></i>&nbsp;Deploy</h3>
      <div class="block">
        Once you've wrapped your URLs with <strong>django-distill</strong> you can deploy
        your static site! Read the
        <a href="{% url 'content:yamlmd_page' page_name='deployment' %}"><i class="fa-solid fa-fw fa-cloud-arrow-up"></i> deployment documentation</a>.
      </div>
    </div>
  </div>
</section>

<section class="container side-pad">
  <h3 class="title"><i class="fa-solid fa-fw fa-star"></i>&nbsp;{{ num_stargazers }} Stargazers</h3>
  <div class="block">
    <div class="columns is-multiline is-flex">
      {% for stargazer in stargazers %}
      <div class="column is-1-fullhd is-1-desktop is-1-widescreen is-1-tablet is-2-mobile">
        <a href="{{ stargazer.url }}" title="GitHub profile for {{ stargazer.name }}" class="image is-square" rel="nofollow" target="_blank">
          <img src="{{ stargazer.avatar }}" alt="GitHub avatar for {{ stargazer.name }}">
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="block">
    <a href="https://github.com/meeb/django-distill/stargazers" rel="nofollow"><i class="fa-brands fa-github"></i> ... and {{ num_stargazers_remaining }} more on GitHub</a>
  </div>
</section>

{% endblock %}

distill_site/content/templates/content/page.html
{% extends 'base.html' %}

{% block page_title %}{{ header.page_title }}{% endblock %}

{% block content %}
<div class="page-top-border">
  <section class="container">
    <h1 class="is-size-1-desktop is-size-2-tablet is-size-3-mobile">{{ header.page_title }}</h1>
  </section>
  <section class="container">
    {{ content|safe }}
  </sction>
</div>
{% endblock %}